#!/bin/bash
for modtype in hyb; do
    for version in 1; do
	for process in bb; do
	    for observation in nb; do
		for seed in {1..5}; do
		    for  platform in nim; do
			make fit.$modtype.$version.$process.$observation.$seed.$platform.Rout &
			done
       		    done
		done	
	    done
        done
    done
